Ans1

In [35]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

A list in Python is a collection of items which can contain elements of multiple data types

An array is a vector containing homogeneous elements i.e. belonging to the same data type. Elements are allocated with contiguous memory locations allowing easy modification

In [36]:
list_

['1', '2', '3', '4', '5']

numeric and string data

In [40]:
arrayList=np.array(list_)

Ans2

In [42]:
def func(a):
    for i in a:
        return type(i)


In [43]:
func(list_)

str

In [44]:
func(arrayList)

numpy.str_

Ans3

In [48]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_, dtype = int)

In [50]:
type(list_)


list

In [47]:
array_list


array([1, 2, 3, 4, 5])

In [ ]:
the list_ and array_list are of differnet data types

Ans4:

In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [24]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
num_array.shape

(2, 3)

In [28]:
num_array.size

6

Ans5

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ans6

In [31]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])